## Config.yml

## Site Settings

## Navigation Nav Title
title: Hearo
subtitle: Semi Smart Glasses Solution
email: hear.o@gmail.com

description: Kacamata pintar dengan teknologi live caption dan kesadaran konteks untuk membantu penyandang disabilitas pendengaran tetap terhubung, kapan saja dan di mana saja

## Url (Host Protocol and Name)
baseurl: "/Hearo" # /Hearo : Change to "" for local development
url: "https://archiseino.github.io"

## Biography Based on 
# author:
street_address: 201 S. Columbia Street
city: Chapel Hill
state: NC
zip_code: 27599
country: United States of America
phone: (919) 590 6000

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 4

# social settings
500px_url:
facebook_url: https://www.facebook.com/cssguncch/
github_url: https://github.com/unc-cs-sg
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url:

# build settings
markdown: kramdown

sass:
  style: compressed
